name: vc-libs
version: '0.1'
summary: Raspberry Pi VC4 libs
description: |
  userspace libs, typically found in /opt/vc

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: armhf

passthrough:
  layout:
    /opt/vc:
      bind: $SNAP/opt/vc

parts:
  vclibs:
    plugin: nil
    override-build: |
      git clone --depth=1 https://github.com/raspberrypi/userland.git .
      ./buildme "$SNAPCRAFT_PART_INSTALL"
    build-packages:
      - cmake
      - g++-arm-linux-gnueabihf
